# Generated by Django 5.1.3 on 2024-11-08 12:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutritions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='NoName', max_length=100)),
                ('age', models.IntegerField(default=0)),
                ('weight', models.FloatField(default=0)),
                ('height', models.FloatField(default=0)),
                ('gender', models.IntegerField(default=0)),
                ('monday', models.CharField(default='none', max_length=500)),
                ('tuesday', models.CharField(default='none', max_length=500)),
                ('wednesday', models.CharField(default='none', max_length=500)),
                ('thursday', models.CharField(default='none', max_length=500)),
                ('friday', models.CharField(default='none', max_length=500)),
                ('saturday', models.CharField(default='none', max_length=500)),
                ('sunday', models.CharField(default='none', max_length=500)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Recipe',
        ),
    ]
