# Generated by Django 5.1.3 on 2024-11-08 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutritions', '0002_userinfo_delete_recipe'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='username',
            field=models.CharField(default='unknown', max_length=120),
        ),
    ]
