# Generated by Django 5.1.3 on 2024-11-08 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nutritions', '0003_userinfo_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='username',
        ),
    ]
