# Generated by Django 5.1.3 on 2024-11-08 17:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutritions', '0004_remove_userinfo_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='friday',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='monday',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='saturday',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='sunday',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='thursday',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='tuesday',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='wednesday',
        ),
        migrations.CreateModel(
            name='UserSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monday_break', models.CharField(default='none', max_length=200)),
                ('monday_lunch', models.CharField(default='none', max_length=200)),
                ('monday_dinner', models.CharField(default='none', max_length=200)),
                ('tuesday_break', models.CharField(default='none', max_length=200)),
                ('tuesday_lunch', models.CharField(default='none', max_length=200)),
                ('tuesday_dinner', models.CharField(default='none', max_length=200)),
                ('wednesday_break', models.CharField(default='none', max_length=200)),
                ('wednesday_lunch', models.CharField(default='none', max_length=200)),
                ('wednesday_dinner', models.CharField(default='none', max_length=200)),
                ('thursday_break', models.CharField(default='none', max_length=200)),
                ('thursday_lunch', models.CharField(default='none', max_length=200)),
                ('thursday_dinner', models.CharField(default='none', max_length=200)),
                ('friday_break', models.CharField(default='none', max_length=200)),
                ('friday_lunch', models.CharField(default='none', max_length=200)),
                ('friday_dinner', models.CharField(default='none', max_length=200)),
                ('saturday_break', models.CharField(default='none', max_length=200)),
                ('saturday_lunch', models.CharField(default='none', max_length=200)),
                ('saturday_dinner', models.CharField(default='none', max_length=200)),
                ('sunday_break', models.CharField(default='none', max_length=200)),
                ('sunday_lunch', models.CharField(default='none', max_length=200)),
                ('sunday_dinner', models.CharField(default='none', max_length=200)),
                ('user_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='nutritions.userinfo')),
            ],
        ),
    ]
