# Generated by Django 5.1.3 on 2024-11-08 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutritions', '0005_remove_userinfo_friday_remove_userinfo_monday_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userschedule',
            old_name='user_info',
            new_name='user',
        ),
        migrations.AddField(
            model_name='userinfo',
            name='username',
            field=models.CharField(default='unknown', max_length=200),
        ),
    ]
