# Generated by Django 5.1.3 on 2024-11-08 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nutritions', '0006_rename_user_info_userschedule_user_userinfo_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='username',
        ),
    ]
