# Generated by Django 5.1.3 on 2024-11-08 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nutritions', '0007_remove_userinfo_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userschedule',
            old_name='user',
            new_name='user_info',
        ),
    ]
