# Generated by Django 5.1.3 on 2024-11-08 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutritions', '0008_rename_user_userschedule_user_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='telegram_id',
            field=models.IntegerField(default=0),
        ),
    ]
