# Generated by Django 5.1.3 on 2024-11-09 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutritions', '0010_alter_userinfo_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='gender',
            field=models.CharField(default='NoInfo', max_length=10),
        ),
    ]
