# Generated by Django 5.1.3 on 2024-11-09 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nutritions', '0011_alter_userinfo_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='name',
        ),
    ]
