# Generated by Django 5.1.3 on 2024-11-09 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutritions', '0013_userinfo_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='preference',
            field=models.CharField(default='NoInfo', max_length=50),
        ),
    ]
