# Generated by Django 5.1.3 on 2024-11-11 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutritions', '0014_userinfo_preference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='preference',
            field=models.IntegerField(default=0),
        ),
    ]
